<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.regalpine.ddd</groupId>
        <artifactId>regalpine-ddd</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>ddd-runtime</artifactId>
    <name>RegalPine DDD :: Runtime</name>
    <description>Runtime Bootstrap, Lifecycle, Component Registry</description>

    <dependencies>
        <dependency>
            <groupId>io.github.regalpine.ddd</groupId>
            <artifactId>ddd-cqrs</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.regalpine.ddd</groupId>
            <artifactId>ddd-event</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.regalpine.ddd</groupId>
            <artifactId>ddd-transaction</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.regalpine.ddd</groupId>
            <artifactId>ddd-messaging</artifactId>
        </dependency>
    </dependencies>
</project>
