package io.github.regalpine.ddd.infrastructure.mybatis.query.ast;

/**
 * Root of the Query AST node hierarchy.
 *
 * <p>Phase XIII §9: all query nodes form a sealed hierarchy.
 * AST nodes are immutable (§62) and generated by the {@code QueryWrapper},
 * then consumed by the {@code QueryTranslator} to produce SQL.</p>
 *
 * @author RegalPine
 */
public sealed interface QueryNode
        permits ConditionNode, LogicalNode, NestedNode,
                OrderNode, SelectNode, PaginationNode {
}
