<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.regalpine.ddd</groupId>
        <artifactId>regalpine-ddd</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>ddd-messaging-rabbitmq</artifactId>
    <name>RegalPine DDD :: Messaging :: RabbitMQ</name>
    <description>RabbitMQ Broker Adapter</description>

    <dependencies>
        <dependency>
            <groupId>io.github.regalpine.ddd</groupId>
            <artifactId>ddd-messaging</artifactId>
        </dependency>
        <dependency>
            <groupId>com.rabbitmq</groupId>
            <artifactId>amqp-client</artifactId>
            <version>5.20.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
