<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.regalpine.ddd</groupId>
        <artifactId>regalpine-ddd</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>ddd-cqrs</artifactId>
    <name>RegalPine DDD :: CQRS</name>
    <description>CommandBus, QueryBus, Middleware Pipeline, Handler Registry</description>

    <dependencies>
        <dependency>
            <groupId>io.github.regalpine.ddd</groupId>
            <artifactId>ddd-application</artifactId>
        </dependency>
    </dependencies>
</project>
